name = "Digest-FarmHash"
license = "mit"
module_maker = "ModuleBuild"
badges = ['travis']
[build]
build_class = "builder::MyBuilder"
[no_index]
directory = ['t', 'xt', 'inc', 'share', 'eg', 'examples', 'author', 'builder', 'vendor']
